Django_Hackerrank/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
	url(r'^$', views.homepage),
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^challenges/', include('Tasks.urls', namespace='Tasks')),
    url(r'leaderboard/(?P<domain>[a-zA-Z0-9]+)/$', views.leaderboard, name='leaderboard'),
    url(r'accounts/', include('django.contrib.auth.urls', namespace="auth")),
]

Tasks/urls.py
from django.conf.urls import url
from django.contrib.auth.urls import *
from . import views

app_name = 'Tasks'

urlpatterns = [
    url(r'^$', views.domains_list, name='index'),
    url(r'^registration/$', views.UserFormView.as_view(), name='registration'),
    url(r'^(?P<domain_name>[a-zA-Z0-9]+)/(?P<subdomain_name>[a-zA-Z]*)/$', views.challenges, name='challenges_list'),
    url(r'^(?P<domain_name>[a-zA-Z0-9]+)/(?P<subdomain_name>[a-zA-Z]*)/(?P<challenge_name>[\w|\W]*)/$',
        views.challenge, name='challenges_list1'),
    # url(r'login/$', views.login_view, name = 'login'),
    # url(r'logout/$', views.logout_view, name = 'logout'),
    url(r'^(?P<domain_name>[a-zA-Z0-9]+)/(?P<subdomain_name>)', views.challenges, name='domain'),
]

Tasks/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class domain(models.Model):
    domain_name = models.CharField(max_length = 50)

    def __str__(self):
        return self.domain_name


class subdomain(models.Model):
    father_domain_name = models.ForeignKey(domain)
    subdomain_name = models.CharField(max_length = 50)

    def __str__(self):
        return str(self.father_domain_name) + '/' + str(self.subdomain_name)


class task(models.Model):
    choices = (('Easy','Easy'), ('Medium', 'Medium'), ('Hard','Hard'))
    father_domain_name = models.ForeignKey(domain)
    father_subdomain_name = models.ForeignKey(subdomain)
    task_name = models.CharField(max_length = 50)
    max_score = models.IntegerField()
    difficulty = models.CharField(max_length = 10, choices = choices, default = 'Easy')
    people_tried = models.IntegerField(default = 0)
    people_succeed = models.IntegerField(default = 0)
    success_rate = models.FloatField(max_length = 4, default = 0)
    task_text = models.TextField(max_length=15000)

    def __str__(self):
        return str(self.task_name).replace('_', " ")


class Test(models.Model):
    father_task_name = models.ForeignKey(task, blank = True)
    test_input = models.TextField(max_length=15000, blank = True)
    test_output = models.TextField(max_length = 15000)

    def __str__(self):
        return str(self.father_task_name)


class TestsLog(models.Model):
    username = models.CharField(max_length = 30)
    timestamp = models.DateTimeField(auto_now = True)
    domain = models.CharField(max_length = 30)
    subdomain = models.CharField(max_length = 30)
    task = models.CharField(max_length = 30)
    result = models.BooleanField()


class User(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    python3 = models.IntegerField(default = 0)
    cpp = models.IntegerField(default = 0)
    c = models.IntegerField(default = 0)
    java = models.IntegerField(default = 0)

    def __str__(self):
        return str(self.user)

Tasks/forms.py
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, get_user_model
from django import forms
# from .models import User as usr


User = get_user_model()


class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

# class UserInfForm(forms.ModelForm):
#    class Meta:
#        model = usr
#        fields = ['photo', 'username', 'first_name', 'last_name', 'python3', 'cpp']


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget = forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        user = authenticate(username=username, password=password)
        return super(UserLoginForm, self).clean(*args, **kwargs)


class TaskForm(forms.Form):
    code = forms.CharField(widget = forms.Textarea(attrs={'placeholder': 'enter code here', 'cols': '70'}))

    def clean(self, *args, **kwargs):
        code = self.cleaned_data.get('code')
        return super(TaskForm, self).clean(*args, **kwargs)

Tasks/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.views.generic import View
from .forms import *
from .models import *
from tester import *


def on_challenge_enter(domain, subdomain, challenge, user):
    hist = TestsLog.objects.filter(domain=domain, subdomain=subdomain, task=challenge, username = user)
    if hist:
        return hist[0]
    else:
        z = challenge
        z.people_tried += 1
        z.success_rate = round(z.people_succeed / z.people_tried * 100, 2)
        z.save()
        q = TestsLog(domain=domain, subdomain=subdomain, task=challenge.task_name, username=user, result = False)
        q.save()
        return q


def challenges(request, domain_name, subdomain_name):
    subs = list(map(lambda x: x.subdomain_name,
                    subdomain.objects.filter(father_domain_name__domain_name__exact = domain_name)))

    context = {'subdomains': subs,
               'challenges': task.objects.filter(father_domain_name__domain_name__exact = domain_name).filter(
                   father_subdomain_name__subdomain_name__exact = subdomain_name),
               'domain': domain_name,
               'subdomain': subdomain_name,
               }
    return render(request, 'challenges.html', context)


def domains_list(request):
    qs = list(domain.objects.all())
    context = {
        'domains': qs,
    }
    z = subdomain.objects.all()
    for i in context['domains']:
        for j in z:
            if j.father_domain_name == i:
                context[i] = j

    return render(request, 'domains.html', context)


def challenge(request, domain_name, subdomain_name, challenge_name):
    cur_task = task.objects.filter(father_domain_name__domain_name__exact=domain_name).filter(
        task_name__exact=challenge_name).get()
    task_form = TaskForm(request.POST or None)

    context = {
        'name': cur_task,
        'task': cur_task.task_text,
        'subdomain': subdomain_name,
        'domain': domain_name,
        'form': task_form,
    }
    if request.user.is_authenticated:
        finished = on_challenge_enter(domain_name, subdomain_name, cur_task, request.user.username)

        if request.method == 'POST':
            if task_form.is_valid():
                code = (TaskForm.clean(task_form)['code'])
            tests_set = cur_task.test_set.all()
            tests = []
            for i in tests_set:
                tests.append([i.test_input.replace('\r', ''), i.test_output.replace('\r', '')])

            filename = str(request.user.username) + '_' + challenge_name
            result = TestProducer(tests, code, filename, domain_name).tests_result
            context['have_result'] = True
            if result[0]:
                solved = True
                for i in result[1]:
                    if not i:
                        solved = False
                if solved:
                    if not finished.result:
                        z = cur_task
                        z.people_succeed += 1
                        z.success_rate = round(z.people_succeed / z.people_tried * 100, 2)
                        z.save()
                        finished.result = True
                        finished.save()
                        q = User.objects.get(user = request.user)
                        if domain_name == 'python3':
                            q.python3 = q.python3 + cur_task.max_score
                        elif domain_name == 'cpp':
                            q.cpp = q.cpp + cur_task.max_score
                        elif domain_name == 'c':
                            q.c = q.c + cur_task.max_score
                        elif domain_name == 'java':
                            q.java = q.java + cur_task.max_score
                        q.save()
                        context['points'] = "You received " + str(cur_task.max_score) + ' points'
                    else:
                        context['points'] = "You have finished this task earlier, so you will not receive any points"
                context['solved'] = solved
                context['result'] = list(enumerate(result[1]))

            else:
                context['error'] = result[1]
    else:
        context['have_result'] = True
        context['error'] = "You don't have permissions to submit. Please Log In."
    return render(request, 'task.html', context)


class UserFormView(View):
    form_class = UserForm
    template_name = 'registration.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit = False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    q = User(user=user)
                    q.save()
                    return redirect('/challenges/')

        return render(request, self.template_name, {'form': form})


def login_view(request):
    next = request.GET.get('next')
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username = username, password = password)
        if user:
           login(request, user)

    if request.method == 'GET':
        return render(request, 'registration.html', {'form': form, 'login': True})
    else:
        return redirect(next)


def logout_view(request):
    logout(request)
    return redirect('/challenges/')

Tasks/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block Title %}Tasks{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Satisfy">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Tasks</a>
            </div>

            <div  class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="">
                        <a href="{% url 'Tasks:index' %}">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
                            Challenge
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'leaderboard' 'python3' %}">
                            <span class="glyphicon glyphicon-stats"></span>&nbsp;
                            Leaderboard
                        </a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if request.user.is_authenticated %}
                    <li class="">
                        <a>
                            <span class="glyphicon glyphicon-user"></span>
                            Hi, {{ request.user.username }}
                        </a>
                    </li>
                    {% if request.user.is_staff %}
                    <li class="">
                        <a href="/admin/Tasks/">
                            <span class="glyphicon glyphicon-cog"></span>
                            Control panel
                        </a>
                    </li>
                    {% endif %}
                    <li class="">
                        <a href="{% url 'Tasks:logout' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                            Log Out
                        </a>
                    </li>
                    {% else %}
                    <li class="">
                        <a href="{% url 'Tasks:login' %}?next={{ request.path }}">
                            <span class="glyphicon glyphicon-log-in"></span>
                            Log in
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>

        </div>
    </nav>
    <div class="middle">
    <div class="content">
    <div class="container-fluid">
        <div class="row">
        {% block body %}
        {% endblock %}
        </div>
    </div>
    </div>
    <br><br><br><br>
    </div>
</body>
</html>

Tasks/templates/challenges.html
{% extends 'base.html' %}
{% block Title %}
    {{ domain }} challenges
{% endblock %}
{% block body %}

    <div class="col-sm-12 col-md-18">
        <div class="panel panel-default">
            <div class="panel-body">
                <a href="{% url 'Tasks:index' %}">All domains</a>
                >
                <a href="{% url 'Tasks:index' %}{{ domain }}/">{{ domain }}</a>
            </div>
        </div>
    </div>

    <br><br>

    <div class="col-sm-12 col-md-2">
        <div class="panel panel-default">
            <div class="panel-body">
                <h4>Subdomains</h4>
            </div>
            {% for i in subdomains %}
                <div class="panel-body">
                    <a href="{% url 'Tasks:index' %}{{ domain }}/{{ i }}/">{{ i }}</a><br>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="col-sm-2 col-md-10">
        <div class="panel panel-default">
            <div class="panel-body">
                <h4>Challenges in {{ subdomain }}</h4>
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-md-10">
        {% for i in challenges %}

            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'Tasks:index' %}{{ domain }}/{{ subdomain }}/{{ i }}/">{{ i }}</a>
                    <br><br>
                    Success Rate: {{ i.success_rate }}% Max Score: {{ i.max_score }} Difficulty: {{ i.difficulty }}
                </div>
            </div>

        {% endfor %}
    </div>
{% endblock %}

Tasks/templates/domains.html
{% extends 'base.html' %}
{% block Title %}
    All domains
{% endblock %}
{% block body %}

    {% for i in domains %}
        <div class="col-sm-12 col-md-5">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{{ i }}/Introduction/">{{ i }}</a>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock %}

Tasks/templates/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>

{% endfor %}

Tasks/templates/registration.html
{% extends 'base.html' %}

{% block body %}

    <div class="col-sm-12 col-md-7">
        <div class="panel panel-default">
            <div class="panel-body">
                <form class="form-horizontal" action="" method="post">
                    {% csrf_token %}
                    {% include 'form-template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>
                    {% if login %}
                        Don't have an account? <a href="{% url 'Tasks:registration' %}">Sign Up</a>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>


{% endblock %}

Tasks/templates/task.html
{% extends 'base.html' %}
{% block Title %}
    {{ domain }} / {{ name }} challenge
{% endblock %}
{% block body %}
    <div class="col-sm-12 col-md-18">
        <div class="panel panel-default">
            <div class="panel-body">
                <a href="{% url 'Tasks:index' %}">All domains</a>
                >
                <a href="{% url 'Tasks:index' %}{{ domain }}/">{{ domain }}</a>
                >
                <a href="{% url 'Tasks:index' %}{{ domain }}/{{ subdomain }}/">{{ subdomain }}</a>
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-md-18">
        <div class="panel panel-default">
            <div class="panel-body">
                {{ task|safe|linebreaks }}
                <form class="form-horizontal" action="" method="post">
                    {% csrf_token %}
                    {% include 'form-template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-5 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% if have_result %}
        <div class="col-sm-12 col-md-18">
            <div class="panel panel-default">
                {% if error %}
                    <div class="panel-body">
                        {{ error }}
                    </div>
                {% else %}
                    <div class="panel-body">
                        {% if solved %}
                            <p>Congrats, you solved this challenge!</p>
                        {% else %}
                            <p>You have not solved</p>
                        {% endif %}
                    </div>
                    <div class="panel-body">
                        {% for i in result %}
                            {% if i.1 %}
                                <span class="glyphicon glyphicon-ok"></span> Test #{{ i.0 }}
                            {% else %}
                                <span class="glyphicon glyphicon-remove"></span> Test #{{ i.0 }}
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div class="panel-body">
                        {{ points }}
                    </div>
                {% endif %}
            </div>
        </div>
    {% endif %}
    </div>
{% endblock %}